name: First Github Actions
run-name: First Github Actions
on:
  push:
    branches:
      - main
      - some-other-branch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          a=5
          b=10
          echo "a=${a} b=${b} Addition $((a+b))"±
