name: Secrets Action
run-name: Secrets Action
on:
  push:
    branches:
      - main
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Poetry and dependencies
        working-directory: ./sample
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install

      - name: Run python program
        working-directory: ./sample
        env:
          MESSAGE: "We are on Github Actions"
          SECRET_PERSONS_NAME: ${{ secrets.SECRET_PERSONS_NAME }}
        run: poetry run start
